[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.11.2"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.10.2"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
